name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  list-examples:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v5

      - id: set-matrix
        run: echo "matrix=$(ls examples/ | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  example-docker:
    needs: list-examples
    runs-on: ubuntu-latest

    permissions:
      packages: write

    strategy:
      matrix:
        example: ${{ fromJson(needs.list-examples.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./examples/${{ matrix.example }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/cerberauth/openid-connect-examples/${{ matrix.example }}:latest
          cache-from: type=registry,ref=ghcr.io/cerberauth/openid-connect-examples/${{ matrix.example }}:latest
          cache-to: type=inline
